name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, json
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev

      - name: Run tests (with dev dependencies)
        run: |
          composer install --prefer-dist --no-progress
          composer test

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
